version: '3.3'
services:
  app:
      image: testapi
      container_name: movi
      depends_on:
            database:
                condition: service_healthy
      ports:
        - 8080:8080
      environment:
       DBNAME: 'db'
       DBUSERNAME: 'root'
       DBPASSWORD: 'password'
       DBHOST: 'database'
       APPPORT: 8080
       DBPORT: 3306
       APIKEY: "1d8aea89"
      links:
       - db

  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: password      
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'

